name: CI/CD Hugging Face

on:
  push:
    branches:
      - main
      - update
  pull_request:

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v3

      # 2️⃣ Installer Node.js pour CML
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # ou la version stable la plus récente

      # 3️⃣ Installer CML via npm
      - name: Install CML
        run: npm install -g cml

      # 4️⃣ Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 5️⃣ Installer les dépendances Python
      - name: Install Python dependencies
        run: make install

      # 6️⃣ Formater le code Python avec Black
      - name: Format code
        run: make format

      # 7️⃣ Entraîner le modèle
      - name: Train model
        run: make train

      # 8️⃣ Générer le rapport et commenter via CML
      - name: Generate report
        run: make eval
        env:
          CML_GITHUB_TOKEN: ${{ secrets.CML_GITHUB_TOKEN }}

      # 9️⃣ Déploiement Hugging Face
      - name: Hugging Face deploy
        run: make deploy
        env:
          HF: ${{ secrets.HF }}