name: Continuous Deployment

# Déclencheur : après la fin du workflow CI
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:  # optionnel, permet de déclencher manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - uses: actions/checkout@v3

      # Déployer vers Hugging Face
      - name: Deployment To Hugging Face
        env:
          HF: ${{ secrets.HF }}   # token Hugging Face
        run: make deploy HF=$HF